// apps/desktop/src/components/settings/Developer/DevExtPathForm.vue
<script setup lang="ts">
import { onMounted, ref } from "vue";
import { Icon } from "@iconify/vue";
import { exists } from "@tauri-apps/plugin-fs";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { useToast } from "@/components/ui/toast";
import { $appConfig, setDevExtentionPath } from "@/lib/stores/appConfig";
import { useStore } from "@nanostores/vue";
import { pathExists } from "tauri-plugin-jarvis-api";
import { onMount } from "nanostores";
// import { loadDevExtManifests, loadExtManifests, $extensionsStore } from "@/lib/stores/extensions";
import { open } from "@tauri-apps/plugin-dialog";
import { Extension } from "@/lib/extension/ext";

const devExt = new Extension("Dev Extensions", $appConfig.get().devExtentionPath, true);
const { toast } = useToast();
const appConfig = useStore($appConfig);
const devExtPath = ref(appConfig.value.devExtentionPath);

const lock = ref(true);

async function pickDirectory() {
  const dir = await open({
    multiple: false,
    directory: true,
  });

  if (dir && (await pathExists(dir))) {
    devExtPath.value = dir;
    setDevExtentionPath(devExtPath.value);
    await devExt.load();
    toast({
      title: "Dev Extension Path Set",
      description: `${devExt.manifests.length} dev extensions loaded.`,
    });
  } else {
    return toast({
      title: "Invalid Path",
      description: "Please enter an existing path",
      variant: "destructive",
    });
  }
}

function clear() {
  devExtPath.value = undefined;
  return setDevExtentionPath(devExtPath.value)
    .then(() => {
      return toast({
        title: "Cleared",
      });
    })
    .catch((err) => {
      return toast({
        title: "Failed To Clear",
        variant: "destructive",
      });
    });
}
</script>

<template>
  <div class="flex w-full items-center gap-1.5">
    <Input
      id="dev-ext-path"
      type="path"
      placeholder="Enter Path"
      v-model="devExtPath"
      :disabled="lock"
    />
    <Button size="sm" type="button" @click="clear">
      Clear
      <Icon icon="material-symbols:delete-outline" class="w-5 h-5 ml-1" />
    </Button>
    <Button size="sm" type="button" @click="pickDirectory">
      Edit
      <Icon icon="flowbite:edit-outline" class="w-5 h-5 ml-1" />
    </Button>
  </div>
</template>

// apps/desktop-svelte/src/lib/components/standalone/settings/DevExtPathForm.svelte
<script lang="ts">
	import { appConfig } from "@/stores"
	import Icon from "@iconify/svelte"
	import { Button, Input } from "@kksh/svelte"
	import { open } from "@tauri-apps/plugin-dialog"
	import { exists } from "@tauri-apps/plugin-fs"
	import { toast } from "svelte-sonner"
	import { superForm, type Infer, type SuperValidated } from "sveltekit-superforms"
	import { zodClient } from "sveltekit-superforms/adapters"
	import { z } from "zod"

	let devExtPath = $state<string | undefined>(undefined)

	async function pickDirectory() {
		const dir = await open({
			multiple: false,
			directory: true
		})
		if (dir && (await exists(dir))) {
			devExtPath = dir
			appConfig.setDevExtensionPath(dir)
			// devExtStore.setExtPath(devExtPath.value)
			// await devExtStore.load()
			// toast.success("Dev Extension Path Set", {
			// 	description: `${devExtStore.manifests.length} dev extensions loaded.`
			// })
		} else {
			return toast.error("Invalid Path")
		}
	}

	function clear() {
		devExtPath = undefined
		appConfig.setDevExtensionPath(null)
		// return appConfig.setDevExtensionPath(devExtPath.value ?? null)
		// .then(() => {
		// 	return toast({
		// 		title: "Cleared"
		// 	})
		// })
		// .catch(() => {
		// 	return toast({
		// 		title: "Failed To Clear",
		// 		variant: "destructive"
		// 	})
		// })
	}
</script>

<form class="flex w-full items-center space-x-2">
	<Input disabled type="text" placeholder="Enter Path" bind:value={$appConfig.devExtensionPath} />
	<Button size="sm" type="button" onclick={clear}>
		Clear
		<Icon icon="material-symbols:delete-outline" class="ml-1 h-5 w-5" />
	</Button>
	<Button size="sm" type="button" onclick={pickDirectory}>
		Edit
		<Icon icon="flowbite:edit-outline" class="ml-1 h-5 w-5" />
	</Button>
</form>
