// apps/desktop-astro/src/components/extension-store/ext-list-item.vue
<script setup lang="ts">
import { Icon } from "@iconify/vue";
import { humanReadableNumber } from "@/lib/utils/format";
import { CircleCheckBigIcon } from "lucide-vue-next";
import { CommandItem } from "@/components/ui/command";
import { ExtItem } from "./types";

const props = defineProps<{
  data: ExtItem;
  installed: boolean;
}>();

const emits = defineEmits<{
  (e: "select"): void;
}>();
</script>
<template>
  <CommandItem :value="props.data" class="" @select="emits('select')">
    <div class="flex justify-between items-center w-full">
      <div class="flex items-center space-x-4">
        <IconMultiplexer :icon="props.data.icon" class="w-6 h-6" />
        <div>
          <div class="font-semibold">{{ props.data.name }}</div>
          <div class="text-xs text-muted-foreground font-mono">
            {{ props.data.short_description }}
          </div>
        </div>
      </div>
      <div class="flex space-x-4">
        <CircleCheckBigIcon v-if="props.installed" class="w-4 text-green-400" />
        <div class="flex items-center space-x-1">
          <Icon icon="ic:round-download" class="w-5 h-5 inline" />
          <span class="w-8 text-center">{{ humanReadableNumber(props.data.downloads) }}</span>
        </div>
      </div>
    </div>
  </CommandItem>
</template>

// apps/desktop-svelte/src/lib/components/extension/ExtListItem.svelte
<script lang="ts">
	import IconMultiplexer from "@/components/common/IconMultiplexer.svelte"
	import * as Command from "@/components/ui/command"
	import { ExtItem } from "@/supabase"
	import { humanReadableNumber } from "@/utils/format"
	import Icon from "@iconify/svelte"
	import { Icon as TIcon } from "@kksh/api/models"
	import { Button } from "@kksh/svelte"
	import { CircleCheckBigIcon, MoveRightIcon } from "lucide-svelte"
	import { parse } from "valibot"

	let {
		ext,
		installedVersion,
		onSelect,
		onUpgrade,
		onInstall
	}: {
		ext: ExtItem
		installedVersion?: string
		onSelect: () => void
		onUpgrade: () => void
		onInstall: () => void
	} = $props()
</script>

<Command.Item class="flex items-center justify-between" {onSelect}>
	<span class="flex items-center space-x-2">
		<IconMultiplexer icon={parse(TIcon, ext.icon)} class="!h-6 !w-6 shrink-0" />
		<span class="flex flex-col gap-0">
			<div class="font-semibold">{ext.name}</div>
			<small class="text-muted-foreground font-mono">{ext.short_description}</small>
		</span>
	</span>

	<span class="flex items-center space-x-1">
		{#if installedVersion}
			{@const upgradable = installedVersion !== ext.version}
			{#if upgradable}
				<Button
					variant="outline"
					size="xs"
					class="flex items-center space-x-1 px-2"
					onclick={(e: MouseEvent) => {
						e.stopPropagation()
						onUpgrade()
					}}
				>
					<Icon icon="carbon:upgrade" class="inline h-5 w-5" />
					<small>{installedVersion}</small>
					<MoveRightIcon class="w-4" />
					<small>{ext.version}</small>
				</Button>
			{:else}
				<CircleCheckBigIcon class="w-4 text-green-400" />
				<small>{ext.version}</small>
			{/if}
		{:else}
			<Button
				variant="ghost"
				size="icon"
				onclick={(e: MouseEvent) => {
					e.stopPropagation()
					onInstall()
				}}
			>
				<Icon icon="ic:round-download" class="inline h-5 w-5" />
			</Button>
		{/if}
		<span class="w-6 text-center">{humanReadableNumber(ext.downloads)}</span>
	</span>
</Command.Item>
