// apps/desktop-svelte/src/lib/components/extension/ExtListItem.svelte
<script lang="ts">
	import IconMultiplexer from "@/components/common/IconMultiplexer.svelte"
	import * as Command from "@/components/ui/command"
	import { ExtItem } from "@/supabase"
	import { humanReadableNumber } from "@/utils/format"
	import Icon from "@iconify/svelte"
	import { Icon as TIcon } from "@kksh/api/models"
	import { Button } from "@kksh/svelte"
	import { CircleCheckBigIcon, MoveRightIcon } from "lucide-svelte"
	import { parse } from "valibot"

	let {
		ext,
		installedVersion,
		onSelect,
		onUpgrade,
		onInstall
	}: {
		ext: ExtItem
		installedVersion?: string
		onSelect: () => void
		onUpgrade: () => void
		onInstall: () => void
	} = $props()
</script>

<Command.Item class="flex items-center justify-between" {onSelect}>
	<span class="flex items-center space-x-2">
		<IconMultiplexer icon={parse(TIcon, ext.icon)} class="!h-6 !w-6 shrink-0" />
		<span class="flex flex-col gap-0">
			<div class="font-semibold">{ext.name}</div>
			<small class="text-muted-foreground font-mono">{ext.short_description}</small>
		</span>
	</span>

	<span class="flex items-center space-x-1">
		{#if installedVersion}
			{@const upgradable = installedVersion !== ext.version}
			{#if upgradable}
				<Button
					variant="outline"
					size="xs"
					class="flex items-center space-x-1 px-2"
					onclick={(e: MouseEvent) => {
						e.stopPropagation()
						onUpgrade()
					}}
				>
					<Icon icon="carbon:upgrade" class="inline h-5 w-5" />
					<small>{installedVersion}</small>
					<MoveRightIcon class="w-4" />
					<small>{ext.version}</small>
				</Button>
			{:else}
				<CircleCheckBigIcon class="w-4 text-green-400" />
				<small>{ext.version}</small>
			{/if}
		{:else}
			<Button
				variant="ghost"
				size="icon"
				onclick={(e: MouseEvent) => {
					e.stopPropagation()
					onInstall()
				}}
			>
				<Icon icon="ic:round-download" class="inline h-5 w-5" />
			</Button>
		{/if}
		<span class="w-6 text-center">{humanReadableNumber(ext.downloads)}</span>
	</span>
</Command.Item>

// apps/desktop/components/extension-store/ext-list-item.vue
<script setup lang="ts">
import IconMultiplexer from "@/components/IconMultiplexer.vue"
import { humanReadableNumber } from "@/lib/utils/format"
import { IconEnum } from "@kksh/api/models"
import { Button } from "@kksh/vue"
import { CommandItem } from "~/components/ui/command"
import { ArrowRightIcon, CircleCheckBigIcon, MoveRightIcon } from "lucide-vue-next"
import { ExtItem } from "./types"

const props = defineProps<{
	data: ExtItem
	installedVersion?: string
	installed: boolean
	upgradeable: boolean
}>()

const emits = defineEmits<{
	(e: "select"): void
	(e: "upgrade"): void
}>()

function onUpgradeClicked(e: MouseEvent) {
	e.stopPropagation()
	emits("upgrade")
}
</script>
<template>
	<CommandItem :value="props.data" class="" @select="emits('select')">
		<div class="flex w-full items-center justify-between">
			<div class="flex items-center space-x-4">
				<IconMultiplexer :icon="props.data.icon" class="h-6 w-6" />
				<div>
					<div class="font-semibold">{{ props.data.name }}</div>
					<div class="text-muted-foreground font-mono text-xs">
						{{ props.data.short_description }}
					</div>
				</div>
			</div>
			<div class="flex items-center space-x-2">
				<CircleCheckBigIcon v-if="props.installed" class="w-4 text-green-400" />
				<Button
					v-if="props.upgradeable"
					class="flex items-center space-x-1 px-2"
					variant="outline"
					@click="onUpgradeClicked"
				>
					<small>{{ props.installedVersion }}</small>
					<MoveRightIcon class="w-4" />
					<small>{{ props.data.version }}</small>
				</Button>
				<small v-else>{{ props.data.version }}</small>
				<div class="flex items-center space-x-1">
					<Button v-if="!props.installed" variant="ghost" size="icon">
						<Icon name="ic:round-download" class="inline h-5 w-5" />
					</Button>
					<span class="w-8 text-center">{{ humanReadableNumber(props.data.downloads) }}</span>
				</div>
			</div>
		</div>
	</CommandItem>
</template>
