// apps/desktop/pages/set-dev-ext-path.vue
<script setup lang="ts">
import DevExtPathForm from "@/components/settings/Developer/DevExtPathForm.vue"
import { Button } from "@kksh/vue/button"
import { ArrowLeftIcon } from "@radix-icons/vue"
import { onKeyStroke } from "@vueuse/core"

onKeyStroke("Escape", (e) => {
	e.preventDefault()
	onBack()
})

function onBack() {
	navigateTo("/")
}
</script>
<template>
	<main class="container h-screen w-screen pt-10">
		<div class="absolute left-0 top-0 h-10 w-screen" data-tauri-drag-region />
		<Button variant="outline" size="icon" class="absolute left-2 top-2 z-50" @click="onBack">
			<ArrowLeftIcon />
		</Button>
		<h2 class="text-2xl font-bold">Set Dev Extension Path</h2>
		<p>This is where your extensions will be installed.</p>
		<DevExtPathForm />
	</main>
</template>

// apps/desktop-svelte/src/routes/settings/set-dev-ext-path/+page.svelte
<script lang="ts">
	import DevExtPathForm from "@/components/standalone/settings/DevExtPathForm.svelte"
	import { goBackOnEscape } from "@/utils/key"
	import { goBack } from "@/utils/route"
	import { Button } from "@kksh/svelte"
	import { ArrowLeftIcon } from "lucide-svelte"
</script>

<svelte:window on:keydown|preventDefault={goBackOnEscape} />
<Button variant="outline" size="icon" class="absolute left-2 top-2 z-50" onclick={goBack}>
	<ArrowLeftIcon class="h-4 w-4" />
</Button>
<div class="absolute left-0 top-0 h-10 w-screen" data-tauri-drag-region></div>
<main class="container pt-10">
	<h2 class="text-2xl font-bold">Set Dev Extension Path</h2>
	<p>This is where your extensions will be installed.</p>
	<DevExtPathForm />
</main>
